name: "services-telemetry"
services:
    db:
        image: "postgres:18-alpine"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}}"]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432/tcp
